//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilitaryConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;BuildingElements&quot;: [],
        ///    &quot;Gains&quot;: [
        ///        {
        ///            &quot;Name&quot;: &quot;БТМ-3&quot;,
        ///            &quot;Description&quot;: &quot;&quot;,
        ///            &quot;Amount&quot;: 0,
        ///            &quot;TrenchPerformance&quot;: 500.0,
        ///            &quot;PitPerformance&quot;: 0.0,
        ///            &quot;IsDefault&quot;: true,
        ///            &quot;Id&quot;: 8359
        ///        },
        ///        {
        ///            &quot;Name&quot;: &quot;ПЗМ-2&quot;,
        ///            &quot;Description&quot;: &quot;&quot;,
        ///            &quot;Amount&quot;: 0,
        ///            &quot;TrenchPerformance&quot;: 120.0,
        ///            &quot;PitPerformance&quot;: 90.0,
        ///            &quot;IsDefault&quot;: true,
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FortificationConfiguration {
            get {
                return ResourceManager.GetString("FortificationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ColorThemes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Темная&quot;,
        ///      &quot;MainMainColor&quot;: &quot;#0D1B2A&quot;,
        ///      &quot;MainSecondaryColor&quot;: &quot;#1B263B&quot;,
        ///      &quot;MainForeColor&quot;: &quot;#778DA9&quot;,
        ///      &quot;SecondaryMainColor&quot;: &quot;#778DA9&quot;,
        ///      &quot;SecondarySecondaryColor&quot;: &quot;#778DA9&quot;,
        ///      &quot;SecondaryForeColor&quot;: &quot;#0D1B2A&quot;,
        ///      &quot;IconType&quot;: 0
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;Министерство Обороны РБ&quot;,
        ///      &quot;MainMainColor&quot;: &quot;#ffffff&quot;,
        ///      &quot;MainSecondaryColor&quot;: &quot;#3b5430&quot;,
        ///      &quot;MainForeColor&quot;: &quot;#000000&quot;,
        ///      &quot;SecondaryMainColor&quot;: &quot;#5974 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
    }
}
